// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Dub Dub Circle",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Dub Dub Circle",
            targets: ["AppModule"],
            bundleIdentifier: "com.omchachad.Dub-Dub-Circle",
            teamIdentifier: "2UM97849VB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "Please allow Photo Library access so that Dub Dub Circle can store details about your selected memories.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.v5]
)